# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import entry.models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='entry',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=entry.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='entry',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
