# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_doc'),
        ('entry', '0002_auto_20161125_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='calories',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='food_group',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='servings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
    ]
