# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20161128_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='food_group',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='servings',
        ),
    ]
