# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20161128_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
        migrations.AddField(
            model_name='entry',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
