# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20161130_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='meal_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
