# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_first_name', models.CharField(max_length=35)),
                ('p_last_name', models.CharField(max_length=35)),
                ('p_birth_date', models.CharField(max_length=35)),
            ],
        ),
    ]
