# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='p_user_name',
            field=models.CharField(default=20160101, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
