# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20161129_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doc',
        ),
        migrations.AddField(
            model_name='patient',
            name='doc_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_password',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
