# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20161129_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doc_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
